package stage

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"bofbench/internal/argpack"
	"bofbench/internal/artifact"
)

type Result struct {
	Target   string   `json:"target"`
	Object   string   `json:"object"`
	Output   string   `json:"output"`
	Manifest string   `json:"manifest,omitempty"`
	Files    []string `json:"files"`
}

type Manifest struct {
	Name          string         `json:"name"`
	Target        string         `json:"target"`
	Object        string         `json:"object"`
	StagedObject  string         `json:"staged_object"`
	Entrypoint    string         `json:"entrypoint"`
	Arguments     []argpack.Item `json:"arguments,omitempty"`
	GeneratedAt   string         `json:"generated_at"`
	Analysis      string         `json:"analysis,omitempty"`
	AnalysisMD    string         `json:"analysis_md,omitempty"`
	AnalysisError string         `json:"analysis_error,omitempty"`
	LatestReport  []string       `json:"latest_report,omitempty"`
}

func Stage(object, target, entry string, args []argpack.Item) (Result, error) {
	if entry == "" {
		entry = "go"
	}
	name := baseName(object)
	root := filepath.Join("stage", fmt.Sprintf("%s-%s", name, target))
	if err := os.RemoveAll(root); err != nil {
		return Result{}, err
	}
	if err := os.MkdirAll(filepath.Join(root, "objects"), 0o755); err != nil {
		return Result{}, err
	}
	dstObj := filepath.Join(root, "objects", filepath.Base(object))
	if err := copyFile(object, dstObj); err != nil {
		return Result{}, err
	}
	var files []string
	manifest := Manifest{
		Name:         name,
		Target:       target,
		Object:       object,
		StagedObject: filepath.ToSlash(filepath.Join("objects", filepath.Base(object))),
		Entrypoint:   entry,
		Arguments:    args,
		GeneratedAt:  time.Now().UTC().Format(time.RFC3339),
	}
	add := func(path string) {
		rel, err := filepath.Rel(root, path)
		if err == nil {
			files = append(files, filepath.ToSlash(rel))
		}
	}
	add(dstObj)
	reportFiles, err := writeReports(root, object, entry, name)
	if err != nil {
		return Result{}, err
	}
	for _, file := range reportFiles {
		add(file)
		rel, _ := filepath.Rel(root, file)
		rel = filepath.ToSlash(rel)
		switch filepath.Base(file) {
		case "analysis.json":
			manifest.Analysis = rel
		case "analysis.md":
			manifest.AnalysisMD = rel
		case "analysis-error.txt":
			b, _ := os.ReadFile(file)
			manifest.AnalysisError = strings.TrimSpace(string(b))
		default:
			if strings.HasPrefix(rel, "reports/latest-") {
				manifest.LatestReport = append(manifest.LatestReport, rel)
			}
		}
	}
	switch target {
	case "cobaltstrike":
		p := filepath.Join(root, name+".cna")
		if err := os.WriteFile(p, []byte(cobaltStrike(name, filepath.Base(object), entry, args)), 0o644); err != nil {
			return Result{}, err
		}
		add(p)
	case "sliver":
		p := filepath.Join(root, "sliver-extension.json")
		if err := writeJSON(p, map[string]any{
			"name":         name,
			"entrypoint":   entry,
			"object":       "objects/" + filepath.Base(object),
			"arguments":    args,
			"generated_at": time.Now().UTC().Format(time.RFC3339),
		}); err != nil {
			return Result{}, err
		}
		add(p)
	case "raw":
		p := filepath.Join(root, "operator-notes.md")
		if err := os.WriteFile(p, []byte(rawNotes(object, entry, args)), 0o644); err != nil {
			return Result{}, err
		}
		add(p)
	default:
		return Result{}, fmt.Errorf("unknown stage target %q", target)
	}
	readmePath := filepath.Join(root, "README.md")
	if err := os.WriteFile(readmePath, []byte(stageReadme(target, object, entry, args)), 0o644); err != nil {
		return Result{}, err
	}
	add(readmePath)
	manifestPath := filepath.Join(root, "manifest.json")
	if err := writeJSON(manifestPath, manifest); err != nil {
		return Result{}, err
	}
	add(manifestPath)
	zipPath := root + ".zip"
	if err := zipDir(root, zipPath); err != nil {
		return Result{}, err
	}
	files = append(files, filepath.Base(zipPath))
	return Result{Target: target, Object: object, Output: root, Manifest: filepath.ToSlash(filepath.Join(root, "manifest.json")), Files: files}, nil
}

func cobaltStrike(name, objectFile, entry string, args []argpack.Item) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by bofbench\n")
	fmt.Fprintf(&b, "alias %s {\n", safeAlias(name))
	b.WriteString("\tlocal('$handle $data $args');\n")
	fmt.Fprintf(&b, "\t$handle = openf(script_resource(\"objects/%s\"));\n", objectFile)
	b.WriteString("\t$data = readb($handle, -1);\n\tclosef($handle);\n")
	if len(args) == 0 {
		b.WriteString("\t$args = \"\";\n")
	} else {
		fmt.Fprintf(&b, "\t$args = bof_pack($1, \"%s\"", aggressorFormat(args))
		for i := range args {
			fmt.Fprintf(&b, ", $%d", i+2)
		}
		b.WriteString(");\n")
	}
	fmt.Fprintf(&b, "\tbtask($1, \"Running BOF %s\");\n", name)
	fmt.Fprintf(&b, "\tbeacon_inline_execute($1, $data, \"%s\", $args);\n", entry)
	b.WriteString("}\n")
	return b.String()
}

func aggressorFormat(args []argpack.Item) string {
	var b strings.Builder
	for _, item := range args {
		switch item.Kind {
		case "z":
			b.WriteByte('z')
		case "Z":
			b.WriteByte('Z')
		case "i":
			b.WriteByte('i')
		case "s":
			b.WriteByte('s')
		case "b", "x":
			b.WriteByte('b')
		}
	}
	return b.String()
}

func rawNotes(object, entry string, args []argpack.Item) string {
	return fmt.Sprintf("# Raw BOF Stage\n\n- Object: `%s`\n- Entrypoint: `%s`\n- Args: `%v`\n", object, entry, args)
}

func stageReadme(target, object, entry string, args []argpack.Item) string {
	return fmt.Sprintf("# bofbench %s stage\n\n- Object: `%s`\n- Entrypoint: `%s`\n- Args: `%v`\n- Manifest: `manifest.json`\n- Reports: `reports/`\n\nGenerated at `%s`.\n",
		target, object, entry, args, time.Now().UTC().Format(time.RFC3339))
}

func writeReports(root, object, entry, name string) ([]string, error) {
	reportsDir := filepath.Join(root, "reports")
	if err := os.MkdirAll(reportsDir, 0o755); err != nil {
		return nil, err
	}
	var files []string
	a, err := artifact.Analyze(object, entry)
	if err != nil {
		p := filepath.Join(reportsDir, "analysis-error.txt")
		if writeErr := os.WriteFile(p, []byte(err.Error()+"\n"), 0o644); writeErr != nil {
			return nil, writeErr
		}
		files = append(files, p)
	} else {
		jsonPath := filepath.Join(reportsDir, "analysis.json")
		mdPath := filepath.Join(reportsDir, "analysis.md")
		if err := writeJSON(jsonPath, a); err != nil {
			return nil, err
		}
		if err := os.WriteFile(mdPath, []byte(artifact.Markdown(a)), 0o644); err != nil {
			return nil, err
		}
		files = append(files, jsonPath, mdPath)
	}
	latest := latestResultFiles(name)
	for _, src := range latest {
		dst := filepath.Join(reportsDir, "latest-"+filepath.Base(src))
		if err := copyFile(src, dst); err != nil {
			return nil, err
		}
		files = append(files, dst)
	}
	return files, nil
}

func latestResultFiles(name string) []string {
	entries, err := os.ReadDir("runs")
	if err != nil {
		return nil
	}
	candidates := map[string]bool{name: true, safeAlias(name): true}
	var best string
	var bestTime time.Time
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		dirName := entry.Name()
		if !matchesRunDir(dirName, candidates) {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		if info.ModTime().After(bestTime) {
			best = filepath.Join("runs", dirName)
			bestTime = info.ModTime()
		}
	}
	if best == "" {
		return nil
	}
	var out []string
	for _, name := range []string{"result.json", "result.md"} {
		p := filepath.Join(best, name)
		if _, err := os.Stat(p); err == nil {
			out = append(out, p)
		}
	}
	return out
}

func matchesRunDir(dirName string, candidates map[string]bool) bool {
	for name := range candidates {
		if strings.HasSuffix(dirName, "-run-"+name) || strings.HasSuffix(dirName, "-test-"+name) {
			return true
		}
	}
	return false
}

func baseName(object string) string {
	base := filepath.Base(object)
	base = strings.TrimSuffix(base, filepath.Ext(base))
	base = strings.TrimSuffix(base, ".x64")
	base = strings.TrimSuffix(base, ".x86")
	return base
}

func safeAlias(name string) string {
	return strings.NewReplacer("-", "_", ".", "_").Replace(name)
}

func writeJSON(path string, v any) error {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	b = append(b, '\n')
	return os.WriteFile(path, b, 0o644)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func zipDir(root, zipPath string) error {
	out, err := os.Create(zipPath)
	if err != nil {
		return err
	}
	defer out.Close()
	zw := zip.NewWriter(out)
	defer zw.Close()
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		w, err := zw.Create(filepath.ToSlash(rel))
		if err != nil {
			return err
		}
		in, err := os.Open(path)
		if err != nil {
			return err
		}
		defer in.Close()
		_, err = io.Copy(w, in)
		return err
	})
}
